services:
    BeckUp\GoogleCaptchaBundle\Service\GoogleCaptchaService:
        arguments:
            $params: '@parameter_bag'
        tags: []

    # Automatically register the bundle
    BeckUp\GoogleCaptchaBundle\GoogleCaptchaBundle: ~ 